const ACTIVITY_TYPE = [
  "update_project",
  "archive_project",
  "unarchive_project",
  "member_join_project",
  "member_left_project",
  "change_role_member_project",
  "remove_member_project",
  "create_taskgroup",
  "update_taskgroup",
  "archive_taskgroup",
  "unarchive_taskgroup",
  "remove_taskgroup",
  "create_task",
  "move_task",
  "update_task",
  "archive_task",
  "unarchive_task",
  "remove_task",
  "assign_task",
  "unassign_task",
  "approval_task",
  "comment_task",
  "add_attachment_task",
  "remove_attachment_task",
];

module.exports = {
  ACTIVITY_TYPE,
};
